const { addGroupe } = require('./addGroupe')
const { deleteGroupe } = require('./deleteGroupe')
const { editGroupe } = require('./editGroupe')
const { getAllGroupes } = require('./getAllGroupes')
const { getGroupesByAcademy } = require('./getGroupesByAcademy')
const { getPlayers } = require('./getPlayers')
const { addplayersToGroup } = require('./addplayersToGroup')
const { retirerPlayer } = require('./retirerPlayer')
const { getGroupesByCoachId } = require('./getGroupesByCoachId')
const { getCoachByPlayerId } = require('./getCoachByPlayerId')
const { getPlayersWithState } = require('./getPlayersWithState')

exports.getCoachByPlayerId = getCoachByPlayerId
exports.getGroupesByCoachId = getGroupesByCoachId
exports.addGroupe = addGroupe
exports.addGroupe = addGroupe
exports.deleteGroupe = deleteGroupe
exports.editGroupe = editGroupe
exports.getAllGroupes = getAllGroupes
exports.getGroupesByAcademy = getGroupesByAcademy
exports.getPlayers = getPlayers
exports.addplayersToGroup = addplayersToGroup
exports.retirerPlayer = retirerPlayer
exports.getPlayersWithState = getPlayersWithState
