const { confirmRegister } = require('./confirmRegister')
const { connectedUser } = require('./connectedUser')
const { deleteAccount } = require('./deleteAccount')
const { login } = require('./login')
const { logout } = require('./logout')
const { register } = require('./register')
const { requestResetPassword } = require('./requestResetPassword')
const { resendEmailConfirmation } = require('./resendEmailConfirmation')
const { resetPassword } = require('./resetPassword')
const { registerCoach } = require('./registerCoach')
const { getUsersByRole } = require('./getUsersByRole')
const { registerPlayer } = require('./registerPlayer')
const { updateUserInfo } = require('./updateUserInfo')
const { getNotificationToken } = require('./getNotificationToken')
const { updateNotificationToken } = require('./updateNotificationToken')
const { editPassword } = require('./editPassword')
const { updateUserImage } = require('./updateUserImage')
const { updateOwnerInfo } = require('./updateOwnerInfo')
const { updateCoachInfo } = require('./updateCoachInfo')
const { updatePlayerInfo } = require('./updatePlayerInfo')

exports.confirmRegister = confirmRegister
exports.connectedUser = connectedUser
exports.deleteAccount = deleteAccount
exports.login = login
exports.logout = logout
exports.register = register
exports.requestResetPassword = requestResetPassword
exports.resendEmailConfirmation = resendEmailConfirmation
exports.resetPassword = resetPassword
exports.registerCoach = registerCoach
exports.getUsersByRole = getUsersByRole
exports.registerPlayer = registerPlayer
exports.updateUserInfo = updateUserInfo
exports.getNotificationToken = getNotificationToken
exports.updateNotificationToken = updateNotificationToken
exports.editPassword = editPassword
exports.updateOwnerInfo = updateOwnerInfo
exports.updateUserImage = updateUserImage
exports.updateCoachInfo = updateCoachInfo
exports.updatePlayerInfo = updatePlayerInfo
