const moment = require('moment')
const startOfWeek = +moment()
  .startOf('week')
  .utcOffset(1)
  .hours(0)
  .minutes(0)
  .seconds(0)
  .milliseconds(0)
const endOfWeek = +moment()
  .endOf('week')
  .utcOffset(1)
  .hours(23)
  .minutes(59)
  .seconds(59)
  .milliseconds(99)
const startOfDay = +moment()
  .startOf('day')
  .utcOffset(1)
  .hours(0)
  .minutes(0)
  .seconds(0)
  .milliseconds(0)
const endOfDay = +moment()
  .endOf('day')
  .utcOffset(1)
  .hours(23)
  .minutes(59)
  .seconds(59)
  .milliseconds(99)
const startOfMonth = +moment()
  .startOf('month')
  .utcOffset(1)
  .hours(0)
  .minutes(0)
  .seconds(0)
  .milliseconds(0)
const endOfMonth = +moment()
  .endOf('month')
  .utcOffset(1)
  .hours(23)
  .minutes(59)
  .seconds(59)
  .milliseconds(99)

exports.startOfWeek = startOfWeek
exports.endOfWeek = endOfWeek
exports.startOfDay = startOfDay
exports.endOfDay = endOfDay
exports.startOfMonth = startOfMonth
exports.endOfMonth = endOfMonth
