const auth = require('./auth')
const academy = require('./academy')
const groupe = require('./groupe')
const event = require('./event')
const materiel = require('./materiel')
const handleRole = require('./handleRole')
const eventReview = require('./eventReview')
const finance = require('./finance')
const abonnement = require('./abonnement')
const stat = require('./stat')
const coachReview = require('./coachReview')

//const error = require('../middleware/error')

module.exports = (app) => {
  app.use('/api/auth', auth)
  app.use('/api/academy', academy)
  app.use('/api/groupe', groupe)
  app.use('/api/event', event)
  app.use('/api/materiel', materiel)
  app.use('/api/handleRole', handleRole)
  app.use('/api/eventReview', eventReview)
  app.use('/api/financials', finance)
  app.use('/api/abonnement', abonnement)
  app.use('/api/stat', stat)
  app.use('/api/coachReview', coachReview)
  // app.use(error)
}
