const { addEvent } = require('./addEvent')
const { deleteEvent } = require('./deleteEvent')
const { editEvent } = require('./editEvent')
const { getAllEvents } = require('./getAllEvents')
const { getEventsByGroupe } = require('./getEventsByGroupe')
const { getEventsByAcademy } = require('./getEventsByAcademy')
const { getEventsByCoach } = require('./getEventsByCoach')
const { getEventsByPlayer } = require('./getEventsByPlayer')
exports.addEvent = addEvent
exports.deleteEvent = deleteEvent
exports.editEvent = editEvent
exports.getAllEvents = getAllEvents
exports.getEventsByGroupe = getEventsByGroupe
exports.getEventsByAcademy = getEventsByAcademy
exports.getEventsByCoach = getEventsByCoach
exports.getEventsByPlayer = getEventsByPlayer
